// category
const LOADING_CATEGORIES_DATA = "LOADING_CATEGORIES_DATA";
const SET_CATEGORIES_DATA = "SET_CATEGORIES_DATA";
const SET_CATEGORIES_ERROR = "SET_CATEGORIES_ERRORS";

// stocks
const LOADING_STOCK_DATA = "LOADING_STOCK_DATA";
const SET_STOCKS_DATA = "SET_STOCKS_DATA";
const SET_STOCK_ERRORS = "SET_STOCK_ERRORS";
const SET_STOCK_SUCCESS = "SET_STOCK_SUCCESS";

// auth
const IS_AUTHENTICATED = "IS_AUTHENTICATED";
const SET_AUTH_ERRORS = "SET_AUTH_ERRORS";

export {
    // CATEGORIES
    LOADING_CATEGORIES_DATA,
    SET_CATEGORIES_ERROR,
    SET_CATEGORIES_DATA,

    // STOCKS
    LOADING_STOCK_DATA,
    SET_STOCKS_DATA,
    SET_STOCK_ERRORS,
    SET_STOCK_SUCCESS,

    // AUTH
    IS_AUTHENTICATED,
    SET_AUTH_ERRORS,
};
