const LOADING_DATA = "LOADING_DATA";
const SET_STOCKS_DATA = "SET_STOCKS_DATA";
const SET_CATEGORIES_DATA = "SET_CATEGORIES_DATA";
const SET_STOCK_ERRORS = "SET_STOCK_ERRORS";

export { LOADING_DATA, SET_CATEGORIES_DATA, SET_STOCKS_DATA, SET_STOCK_ERRORS };
